# Generated by Django 3.1.7 on 2021-05-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessfulLogins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('browser', models.CharField(max_length=100)),
                ('ip', models.CharField(max_length=100)),
            ],
        ),
    ]
