# Generated by Django 3.1.7 on 2021-05-09 19:01

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0002_auto_20210509_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abouts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Motto', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('Vision', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('Mission', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('CoreValues', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Careers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=500)),
                ('Description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('Status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SchoolName', models.CharField(max_length=1000)),
                ('SchoolLogo', models.ImageField(upload_to='Contacts')),
                ('PhoneNumbers', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=200)),
                ('Emails', models.CharField(max_length=200)),
                ('PrincipalName', models.CharField(max_length=500)),
                ('PrincipalWords', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('PrincipalPic', models.ImageField(upload_to='Contacts')),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Topics', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('DepartmentHead', models.CharField(max_length=100)),
                ('HoDPic', models.ImageField(upload_to='Departments')),
                ('Status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=2000)),
                ('Link', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('hasSub', models.IntegerField(default=0)),
                ('Status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Sliders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Intro', models.CharField(max_length=1000)),
                ('Desc', models.CharField(max_length=1000)),
                ('Image', models.ImageField(upload_to='Sliders')),
                ('Active', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=1000)),
                ('Email', models.CharField(max_length=1000)),
                ('Status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='SubMenus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubmenuName', models.CharField(max_length=100)),
                ('Status', models.IntegerField(default=1)),
                ('MainMenu', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='School.menus')),
            ],
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PageTitle', models.CharField(max_length=300)),
                ('PageSlug', models.CharField(max_length=1000)),
                ('PageContent', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('FeaturedImage', models.ImageField(upload_to='Pages')),
                ('Status', models.IntegerField(default=1)),
                ('ArticleMenu', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='School.menus')),
                ('ArticleSubMenu', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='School.submenus')),
            ],
        ),
    ]
