# Generated by Django 3.1.7 on 2021-05-10 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0003_abouts_careers_contacts_departments_links_menus_pages_sliders_submenus_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menus',
            name='hasSub',
            field=models.IntegerField(choices=[(1, 'Hassubmenu'), (0, 'Hasnone')], default=0),
        ),
    ]
