# Generated by Django 3.1.7 on 2021-05-10 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0004_auto_20210510_0335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sliders',
            old_name='Image',
            new_name='DisplayImage',
        ),
    ]
