# Generated by Django 3.1.7 on 2021-05-10 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0005_auto_20210510_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliders',
            name='Active',
            field=models.IntegerField(choices=[(1, 'Active'), (0, 'Notactive')], default=0),
        ),
    ]
